### ISSUE TITLE
入力された質問のトークン数を表示したい

### ISSUE THREAD

**Issue by diffshare** [diffshare/chatgpt-electron-app#25]
[人間] ChatGPTのtokenの仕組みを調査。

以下のトークナイザーを用いていることがわかった。

https://github.com/openai/tiktoken star 3.3k

他のトークナイザーに比べて高速らしい。
これのnodeの移植版が2つくらい見つかった。

- https://github.com/dqbd/tiktoken star 88
- https://github.com/openai/tiktoken star 25

starが多い dpbd/tiktoken を利用する方法を検討する。

**Comment by diffshare** [comment]
dpbd/tiktoken を利用するが、下記エラーが発生

```
Uncaught TypeError: wasm.__wbindgen_add_to_stack_pointer is not a function
    at encoding_for_model (tiktoken_bg.js:197:1)
    at ./src/App.tsx (App.tsx:76:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./src/index.tsx (App.tsx:378:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at startup:7:1
    at startup:7:1
```

**Comment by diffshare** [comment]
https://github.com/diffshare/chatgpt-electron-app/issues/25#issuecomment-1493189439
のエラーは
https://github.com/dqbd/tiktoken/tree/main/js#create-react-app
の対応を行うことで解決

**Comment by diffshare** [comment]
[gpt-4]
次のコードのようにuserInputのトークン数を表示する変更を行いました。この変更のpull requestの内容をテンプレートに従って出力してください。
...
## Pull Requestの内容

### 概要
- ユーザーが入力したテキストのトークン数を表示する変更を行いました。

### 変更点
- `useState`フックを使用して、`userInputTokenCount`ステートを追加しました。
- `countTokens`関数を定義し、`userInput`が更新されるたびに実行して、トークン数を計算するようにしました。
- `userInputTokenCount`を表示する要素を追加しました。

### 動作確認方法
1. アプリを起動します。
2. 入力欄に文字を入力すると、文字数とトークン数が表示されます。

**Comment by diffshare** [comment]
ChatGPT(gpt-3.5-turbo)にトークン数を聞いて、正しい様子だったので、正しいと判断する。

<img width="723" alt="image" src="https://user-images.githubusercontent.com/2221199/229326547-b8fd1e84-fc07-493e-91b8-60fdeda6aaff.png">
